apiVersion: v1
kind: PersistentVolume
metadata:
  name: flowise-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: flowise-disk
    fsType: ext4
